name: BitcoinAPI
version: '${project.version}'
main: de.bitcoinclient.BitcoinAPI
api-version: 1.19
authors: [ BitcoinClient ]
description: API von BitcoinClient
commands:
  stop:
    permission: bitcoinapi.command.stop
  gamemode:
    aliases: [gm]
    permission: